insert into Song (id, title, artist, genre, length) values (1, 'Not Here to Be Loved (Je ne suis pas là pour être aimé)', 'Demetre Hellwich', 'Drama|Romance', 45);
insert into Song (id, title, artist, genre, length) values (2, 'Soupe aux Choux, La', 'Aurelie Lavens', 'Comedy', 95);
insert into Song (id, title, artist, genre, length) values (3, 'Dragon Missile, The (Fei long zhan)', 'Stace Silmon', 'Action', 92);
insert into Song (id, title, artist, genre, length) values (4, 'Death Wish 5: The Face of Death', 'Myrah Emons', 'Action|Drama', 7);
insert into Song (id, title, artist, genre, length) values (5, 'Girl, The', 'Ingra Gretton', 'Drama', 60);
insert into Song (id, title, artist, genre, length) values (6, 'West Side Story', 'Dewie Ruprecht', 'Drama|Musical|Romance', 97);
insert into Song (id, title, artist, genre, length) values (7, 'In Vogue: The Editor?s Eye', 'Fidole D''Acth', 'Documentary', 44);
insert into Song (id, title, artist, genre, length) values (8, 'Just a Kiss', 'Sheffield Chislett', 'Comedy|Romance', 82);
insert into Song (id, title, artist, genre, length) values (9, 'Gabrielle', 'Naomi Brok', 'Drama|Romance', 73);
insert into Song (id, title, artist, genre, length) values (10, 'Dangerous Ground', 'Paco Shalloo', 'Drama', 22);
insert into Song (id, title, artist, genre, length) values (11, 'Recipe for Love', 'Ileana Tickner', 'Romance', 33);
insert into Song (id, title, artist, genre, length) values (12, 'Bad Blood (Mauvais sang)', 'Von Critzen', 'Crime|Drama|Romance', 79);
insert into Song (id, title, artist, genre, length) values (13, 'Nola', 'Reube Spratling', 'Drama', 69);
insert into Song (id, title, artist, genre, length) values (14, 'Piano Teacher, The (La pianiste)', 'Bonnibelle Groundwater', 'Drama', 68);
insert into Song (id, title, artist, genre, length) values (15, 'Silver Linings Playbook', 'Nappie Sutworth', 'Comedy|Drama', 97);
insert into Song (id, title, artist, genre, length) values (16, 'Podwórka', 'Nels Jakubiak', 'Documentary', 41);
insert into Song (id, title, artist, genre, length) values (17, 'Young Gods (Hymypoika)', 'Star Whale', 'Drama', 86);
insert into Song (id, title, artist, genre, length) values (18, 'Murder by Contract', 'Molly Minocchi', 'Crime|Drama|Film-Noir|Thriller', 49);
insert into Song (id, title, artist, genre, length) values (19, 'Stand Up and Cheer!', 'Cozmo Stannard', 'Comedy|Musical', 19);
insert into Song (id, title, artist, genre, length) values (20, 'Treasure Island', 'Cynthea Leyninye', 'Adventure', 45);
